pub const DAY_IN_LEDGERS: u32 = 17280;
pub const WEEK_IN_LEDGERS: u32 = DAY_IN_LEDGERS * 7;
pub const MONTH_IN_LEDGERS: u32 = DAY_IN_LEDGERS * 30;

// Instance TTL
pub const MAX_INSTANCE_TTL: u32 = MONTH_IN_LEDGERS * 6;
pub const INSTANCE_TTL_THRESHOLD: u32 = MAX_INSTANCE_TTL - MONTH_IN_LEDGERS;

// Persistent TTL
pub const MAX_PERSISTENT_TTL: u32 = MONTH_IN_LEDGERS * 6;
pub const PERSISTENT_TTL_THRESHOLD: u32 = MAX_PERSISTENT_TTL - MONTH_IN_LEDGERS;

// Temporary TTL
pub const MAX_TEMPORARY_TTL: u32 = WEEK_IN_LEDGERS;
pub const TEMPORARY_TTL_THRESHOLD: u32 = MAX_TEMPORARY_TTL - DAY_IN_LEDGERS;

// custom
pub const PRICE_PRECISION: u128 = 10_000_000; //expo = -7;
pub const PRICE_PRECISION_I128: i128 = PRICE_PRECISION as i128;
pub const PRICE_PRECISION_U64: u64 = 1_000_000; //expo = -6;
pub const PRICE_PRECISION_I64: i64 = 1_000_000; //expo = -6;

pub const PERCENTAGE_PRECISION: u128 = 1_000_000; // expo -6 (represents 100%)
pub const PERCENTAGE_PRECISION_I128: i128 = PERCENTAGE_PRECISION as i128;
pub const PERCENTAGE_PRECISION_U64: u64 = PERCENTAGE_PRECISION as u64;
pub const PERCENTAGE_PRECISION_I64: i64 = PERCENTAGE_PRECISION as i64;

// Pool
pub const FEE_MULTIPLIER: u128 = 10_000;

// Pool Router
pub const MAX_POOLS_FOR_PAIR: u32 = 1;
pub const CONSTANT_PRODUCT_FEE_AVAILABLE: [u32; 3] = [10, 30, 100];
