version: "3"
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - task -d ../token build || exit 1
      - task -d ../pool_plane build || exit 1
      - soroban contract build --package pool
      - soroban contract optimize --wasm ../../target/wasm32v1-none/release/pool.wasm --wasm-out ../../target/wasm32v1-none/release/pool.wasm
      - ls -l ../../target/wasm32v1-none/release/*.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    deps:
      - build
    cmd: cargo test --features=slow_tests

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
